/*
Copyright 2019 The Knative Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1alpha1 "github.com/toversus/sample-bindings/pkg/apis/bindings/v1alpha1"
	scheme "github.com/toversus/sample-bindings/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// DatabaseBindingsGetter has a method to return a DatabaseBindingInterface.
// A group's client should implement this interface.
type DatabaseBindingsGetter interface {
	DatabaseBindings(namespace string) DatabaseBindingInterface
}

// DatabaseBindingInterface has methods to work with DatabaseBinding resources.
type DatabaseBindingInterface interface {
	Create(*v1alpha1.DatabaseBinding) (*v1alpha1.DatabaseBinding, error)
	Update(*v1alpha1.DatabaseBinding) (*v1alpha1.DatabaseBinding, error)
	UpdateStatus(*v1alpha1.DatabaseBinding) (*v1alpha1.DatabaseBinding, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.DatabaseBinding, error)
	List(opts v1.ListOptions) (*v1alpha1.DatabaseBindingList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.DatabaseBinding, err error)
	DatabaseBindingExpansion
}

// databaseBindings implements DatabaseBindingInterface
type databaseBindings struct {
	client rest.Interface
	ns     string
}

// newDatabaseBindings returns a DatabaseBindings
func newDatabaseBindings(c *BindingsV1alpha1Client, namespace string) *databaseBindings {
	return &databaseBindings{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the databaseBinding, and returns the corresponding databaseBinding object, and an error if there is any.
func (c *databaseBindings) Get(name string, options v1.GetOptions) (result *v1alpha1.DatabaseBinding, err error) {
	result = &v1alpha1.DatabaseBinding{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("databasebindings").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of DatabaseBindings that match those selectors.
func (c *databaseBindings) List(opts v1.ListOptions) (result *v1alpha1.DatabaseBindingList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.DatabaseBindingList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("databasebindings").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested databaseBindings.
func (c *databaseBindings) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("databasebindings").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a databaseBinding and creates it.  Returns the server's representation of the databaseBinding, and an error, if there is any.
func (c *databaseBindings) Create(databaseBinding *v1alpha1.DatabaseBinding) (result *v1alpha1.DatabaseBinding, err error) {
	result = &v1alpha1.DatabaseBinding{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("databasebindings").
		Body(databaseBinding).
		Do().
		Into(result)
	return
}

// Update takes the representation of a databaseBinding and updates it. Returns the server's representation of the databaseBinding, and an error, if there is any.
func (c *databaseBindings) Update(databaseBinding *v1alpha1.DatabaseBinding) (result *v1alpha1.DatabaseBinding, err error) {
	result = &v1alpha1.DatabaseBinding{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("databasebindings").
		Name(databaseBinding.Name).
		Body(databaseBinding).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *databaseBindings) UpdateStatus(databaseBinding *v1alpha1.DatabaseBinding) (result *v1alpha1.DatabaseBinding, err error) {
	result = &v1alpha1.DatabaseBinding{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("databasebindings").
		Name(databaseBinding.Name).
		SubResource("status").
		Body(databaseBinding).
		Do().
		Into(result)
	return
}

// Delete takes name of the databaseBinding and deletes it. Returns an error if one occurs.
func (c *databaseBindings) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("databasebindings").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *databaseBindings) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("databasebindings").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched databaseBinding.
func (c *databaseBindings) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.DatabaseBinding, err error) {
	result = &v1alpha1.DatabaseBinding{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("databasebindings").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
